stable

diff --git a/ansible/roles/seedbox/templates/stop-transmission.sh.j2 b/ansible/roles/seedbox/templates/stop-transmission.sh.j2
--- a/ansible/roles/seedbox/templates/stop-transmission.sh.j2
+++ b/ansible/roles/seedbox/templates/stop-transmission.sh.j2
@@ -7,6 +7,10 @@ USERNAME="$(jq -r '.username' seedbox-settings.json)"
 
 echo "Stopping transmission"
 transmission-remote localhost:${PORT} -n ${USERNAME}:${PASSWORD} --exit
+if [ $? -ne 0 ];then
+    echo "Cannot stop"
+    exit 0
+fi
 
 #PID=$(cat ~/transmission-daemon/${USERNAME}.pid)
 #kill -9 $PID
